title: Rust Project Template
description: An template project for Rust.
theme: jekyll-theme-slate
# remote_theme: mmistakes/minimal-mistakes
# https://github.com/topics/jekyll-theme
url: https://kagemeka.github.io
lsi: false
safe: true
source: [.]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
