array_width = 31
attr_fn_like_width = 15
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
chain_width = 63
max_width = 79
color = "Auto"

